//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWFE.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Customer1[] customerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerList", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> customerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Customer1[] CustomerDetail(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> CustomerDetailAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int createCustomer(MVCWFE.ServiceReference1.Customer1 Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<int> createCustomerAsync(MVCWFE.ServiceReference1.Customer1 Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Customer1 EditView(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditView", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1> EditViewAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Edit(MVCWFE.ServiceReference1.Customer1 customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EditAsync(MVCWFE.ServiceReference1.Customer1 customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Next", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Customer1[] Next(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Next", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> NextAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/First", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Customer1[] First();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/First", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> FirstAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVCWFE.ServiceReference1.Order[] OrderDetails(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Order[]> OrderDetailsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderAgainstCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OrderAgainstCustomer(MVCWFE.ServiceReference1.Order order, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderAgainstCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task OrderAgainstCustomerAsync(MVCWFE.ServiceReference1.Order order, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddingToOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AddingToOrderDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddingToOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AddingToOrderDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int postOrderDetails(MVCWFE.ServiceReference1.Products orderDetails, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<int> postOrderDetailsAsync(MVCWFE.ServiceReference1.Products orderDetails, int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private string companyNameField;
        
        private string contactNameField;
        
        private string contactTitleField;
        
        private string addressField;
        
        private string cityField;
        
        private string regionField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private Order[] ordersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("ContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContactTitle {
            get {
                return this.contactTitleField;
            }
            set {
                this.contactTitleField = value;
                this.RaisePropertyChanged("ContactTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public Order[] Orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("Orders");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderIDField;
        
        private string customerIDField;
        
        private string shipNameField;
        
        private string shipAddressField;
        
        private string shipCityField;
        
        private string shipRegionField;
        
        private string shipPostalCodeField;
        
        private string shipCountryField;
        
        private OrderDetails[] orderDetailsField;
        
        private Customer1 customerField;
        
        private Order orders1Field;
        
        private Order order1Field;
        
        private Order orders11Field;
        
        private Order order2Field;
        
        private Order orders12Field;
        
        private Order order3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShipName {
            get {
                return this.shipNameField;
            }
            set {
                this.shipNameField = value;
                this.RaisePropertyChanged("ShipName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ShipAddress {
            get {
                return this.shipAddressField;
            }
            set {
                this.shipAddressField = value;
                this.RaisePropertyChanged("ShipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ShipCity {
            get {
                return this.shipCityField;
            }
            set {
                this.shipCityField = value;
                this.RaisePropertyChanged("ShipCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ShipRegion {
            get {
                return this.shipRegionField;
            }
            set {
                this.shipRegionField = value;
                this.RaisePropertyChanged("ShipRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ShipPostalCode {
            get {
                return this.shipPostalCodeField;
            }
            set {
                this.shipPostalCodeField = value;
                this.RaisePropertyChanged("ShipPostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ShipCountry {
            get {
                return this.shipCountryField;
            }
            set {
                this.shipCountryField = value;
                this.RaisePropertyChanged("ShipCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public OrderDetails[] OrderDetails {
            get {
                return this.orderDetailsField;
            }
            set {
                this.orderDetailsField = value;
                this.RaisePropertyChanged("OrderDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Customer1 Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Order Orders1 {
            get {
                return this.orders1Field;
            }
            set {
                this.orders1Field = value;
                this.RaisePropertyChanged("Orders1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Order Order1 {
            get {
                return this.order1Field;
            }
            set {
                this.order1Field = value;
                this.RaisePropertyChanged("Order1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Order Orders11 {
            get {
                return this.orders11Field;
            }
            set {
                this.orders11Field = value;
                this.RaisePropertyChanged("Orders11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Order Order2 {
            get {
                return this.order2Field;
            }
            set {
                this.order2Field = value;
                this.RaisePropertyChanged("Order2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Order Orders12 {
            get {
                return this.orders12Field;
            }
            set {
                this.orders12Field = value;
                this.RaisePropertyChanged("Orders12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Order Order3 {
            get {
                return this.order3Field;
            }
            set {
                this.order3Field = value;
                this.RaisePropertyChanged("Order3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderIDField;
        
        private int productIDField;
        
        private int unitPriceField;
        
        private int quantityField;
        
        private bool discountField;
        
        private Products[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("UnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
                this.RaisePropertyChanged("Discount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Products[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("Products");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Products : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIDField;
        
        private string productNameField;
        
        private int supplierIDField;
        
        private int categoryIDField;
        
        private string quantityPerUnitField;
        
        private int unitPriceField;
        
        private int unitsInStockField;
        
        private int unitsOnOrderField;
        
        private int reorderLevelField;
        
        private bool discontinuedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
                this.RaisePropertyChanged("SupplierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
                this.RaisePropertyChanged("CategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QuantityPerUnit {
            get {
                return this.quantityPerUnitField;
            }
            set {
                this.quantityPerUnitField = value;
                this.RaisePropertyChanged("QuantityPerUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("UnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int UnitsInStock {
            get {
                return this.unitsInStockField;
            }
            set {
                this.unitsInStockField = value;
                this.RaisePropertyChanged("UnitsInStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int UnitsOnOrder {
            get {
                return this.unitsOnOrderField;
            }
            set {
                this.unitsOnOrderField = value;
                this.RaisePropertyChanged("UnitsOnOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ReorderLevel {
            get {
                return this.reorderLevelField;
            }
            set {
                this.reorderLevelField = value;
                this.RaisePropertyChanged("ReorderLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Discontinued {
            get {
                return this.discontinuedField;
            }
            set {
                this.discontinuedField = value;
                this.RaisePropertyChanged("Discontinued");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MVCWFE.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MVCWFE.ServiceReference1.WebService1Soap>, MVCWFE.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCWFE.ServiceReference1.Customer1[] customerList() {
            return base.Channel.customerList();
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> customerListAsync() {
            return base.Channel.customerListAsync();
        }
        
        public MVCWFE.ServiceReference1.Customer1[] CustomerDetail(string id) {
            return base.Channel.CustomerDetail(id);
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> CustomerDetailAsync(string id) {
            return base.Channel.CustomerDetailAsync(id);
        }
        
        public int createCustomer(MVCWFE.ServiceReference1.Customer1 Customer) {
            return base.Channel.createCustomer(Customer);
        }
        
        public System.Threading.Tasks.Task<int> createCustomerAsync(MVCWFE.ServiceReference1.Customer1 Customer) {
            return base.Channel.createCustomerAsync(Customer);
        }
        
        public MVCWFE.ServiceReference1.Customer1 EditView(string id) {
            return base.Channel.EditView(id);
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1> EditViewAsync(string id) {
            return base.Channel.EditViewAsync(id);
        }
        
        public int Edit(MVCWFE.ServiceReference1.Customer1 customer) {
            return base.Channel.Edit(customer);
        }
        
        public System.Threading.Tasks.Task<int> EditAsync(MVCWFE.ServiceReference1.Customer1 customer) {
            return base.Channel.EditAsync(customer);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public MVCWFE.ServiceReference1.Customer1[] Next(string id) {
            return base.Channel.Next(id);
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> NextAsync(string id) {
            return base.Channel.NextAsync(id);
        }
        
        public MVCWFE.ServiceReference1.Customer1[] First() {
            return base.Channel.First();
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Customer1[]> FirstAsync() {
            return base.Channel.FirstAsync();
        }
        
        public MVCWFE.ServiceReference1.Order[] OrderDetails(string id) {
            return base.Channel.OrderDetails(id);
        }
        
        public System.Threading.Tasks.Task<MVCWFE.ServiceReference1.Order[]> OrderDetailsAsync(string id) {
            return base.Channel.OrderDetailsAsync(id);
        }
        
        public void OrderAgainstCustomer(MVCWFE.ServiceReference1.Order order, string id) {
            base.Channel.OrderAgainstCustomer(order, id);
        }
        
        public System.Threading.Tasks.Task OrderAgainstCustomerAsync(MVCWFE.ServiceReference1.Order order, string id) {
            return base.Channel.OrderAgainstCustomerAsync(order, id);
        }
        
        public string[] AddingToOrderDetails() {
            return base.Channel.AddingToOrderDetails();
        }
        
        public System.Threading.Tasks.Task<string[]> AddingToOrderDetailsAsync() {
            return base.Channel.AddingToOrderDetailsAsync();
        }
        
        public int postOrderDetails(MVCWFE.ServiceReference1.Products orderDetails, int id) {
            return base.Channel.postOrderDetails(orderDetails, id);
        }
        
        public System.Threading.Tasks.Task<int> postOrderDetailsAsync(MVCWFE.ServiceReference1.Products orderDetails, int id) {
            return base.Channel.postOrderDetailsAsync(orderDetails, id);
        }
    }
}
